# Generated by Django 5.2.8 on 2025-11-05 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("gcash", "GCash"),
                            ("paymaya", "PayMaya"),
                            ("onsite", "Onsite/Cash"),
                        ],
                        default="gcash",
                        help_text="Payment method",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "txn_id",
                    models.CharField(
                        help_text="Mock transaction ID (e.g., TXN-XXXXXX)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Payment notes or error messages"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        help_text="Linked appointment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
