# Generated by Django 5.2.8 on 2025-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GCashQRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        help_text="GCash 'Receive Payment' QR code image",
                        upload_to="gcash_qr/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="GCash Receive Payment",
                        help_text="Description for this QR code",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this QR code is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GCash QR Code",
                "verbose_name_plural": "GCash QR Codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Whether payment has been verified by admin"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("full", "Full Payment"), ("downpayment", "Downpayment")],
                default="full",
                help_text="Type of payment (full or downpayment)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                help_text="Receipt image for verification",
                null=True,
                upload_to="payment_receipts/",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("gcash", "GCash"),
                    ("pay", "Pay with Receipt"),
                    ("onsite", "Onsite/Cash"),
                ],
                default="gcash",
                help_text="Payment method",
                max_length=20,
            ),
        ),
    ]
