# Generated by Django 5.2.8 on 2025-11-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_gcashqrcode_payment_is_verified_payment_payment_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_content", models.TextField(help_text="HTML content of receipt")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        help_text="Associated payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt",
                "verbose_name_plural": "Receipts",
                "ordering": ["-generated_at"],
            },
        ),
    ]
