# Generated by Django 5.2.8 on 2025-11-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="auto_verified",
            field=models.BooleanField(
                default=False,
                help_text="True if payment was auto-verified on receipt upload",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When payment was verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who verified (null if auto-verified)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
