# Generated by Django 5.1.4 on 2025-12-01 06:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0006_service_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("simple", "Simple Exponential Smoothing"),
                            ("trend", "Trend (Holt's Method)"),
                            ("seasonal", "Seasonal (Holt-Winters)"),
                        ],
                        default="seasonal",
                        help_text="Forecasting method used",
                        max_length=20,
                    ),
                ),
                (
                    "forecast_period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        help_text="Period granularity",
                        max_length=20,
                    ),
                ),
                (
                    "forecast_start_date",
                    models.DateField(help_text="Start date of forecast"),
                ),
                (
                    "forecast_end_date",
                    models.DateField(help_text="End date of forecast"),
                ),
                (
                    "periods_ahead",
                    models.IntegerField(
                        default=7,
                        help_text="Number of periods forecasted ahead",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "forecast_values",
                    models.TextField(help_text="Comma-separated forecast values"),
                ),
                (
                    "confidence_lower",
                    models.TextField(
                        blank=True, help_text="Lower confidence bound values"
                    ),
                ),
                (
                    "confidence_upper",
                    models.TextField(
                        blank=True, help_text="Upper confidence bound values"
                    ),
                ),
                (
                    "accuracy_mae",
                    models.FloatField(
                        default=0.0,
                        help_text="Mean Absolute Error",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "accuracy_mape",
                    models.FloatField(
                        default=0.0,
                        help_text="Mean Absolute Percentage Error",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "accuracy_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Overall accuracy score (0-100)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("increasing", "Increasing"),
                            ("decreasing", "Decreasing"),
                            ("stable", "Stable"),
                        ],
                        default="stable",
                        help_text="Overall trend direction",
                        max_length=20,
                    ),
                ),
                (
                    "trend_strength",
                    models.FloatField(default=0.0, help_text="Trend strength (0-1)"),
                ),
                (
                    "peak_day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Peak day (0=Monday, 6=Sunday)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "peak_hour",
                    models.IntegerField(
                        blank=True,
                        help_text="Peak hour of day (0-23)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service being forecasted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand Forecast",
                "verbose_name_plural": "Demand Forecasts",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("peak_periods", "Peak Periods"),
                            ("low_periods", "Low Periods"),
                            ("seasonality_index", "Seasonality Index"),
                            ("volatility", "Volatility"),
                            ("growth_rate", "Growth Rate"),
                        ],
                        help_text="Type of metric",
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Label for this metric", max_length=255),
                ),
                ("value", models.FloatField(help_text="Metric value")),
                (
                    "insight",
                    models.TextField(
                        blank=True, help_text="Human-readable insight about this metric"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "forecast",
                    models.ForeignKey(
                        help_text="Associated forecast",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="analytics.demandforecast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast Metric",
                "verbose_name_plural": "Forecast Metrics",
                "ordering": ["-value"],
            },
        ),
        migrations.AddIndex(
            model_name="demandforecast",
            index=models.Index(
                fields=["service", "-generated_at"],
                name="analytics_d_service_4aa316_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="demandforecast",
            index=models.Index(
                fields=["forecast_period", "-generated_at"],
                name="analytics_d_forecas_d5accf_idx",
            ),
        ),
    ]
