# Generated by Django 5.2.8 on 2025-11-21 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("action_types", models.JSONField(blank=True, default=list)),
                ("date_from", models.DateTimeField(blank=True, null=True)),
                ("date_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_filters_as_target",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Audit Log Filters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("STATUS_CHANGE", "Status Changed"),
                            ("PAYMENT_UPDATE", "Payment Status Changed"),
                            ("STOCK_ADJUSTMENT", "Stock Adjusted"),
                            ("APPOINTMENT_CANCEL", "Appointment Cancelled"),
                            ("USER_CREATE", "User Created"),
                            ("USER_UPDATE", "User Updated"),
                            ("USER_DELETE", "User Deleted"),
                            ("ROLE_CHANGE", "Role Changed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("USER_DEACTIVATE", "User Deactivated"),
                            ("USER_REACTIVATE", "User Reactivated"),
                            ("LOGIN", "Logged In"),
                            ("LOGOUT", "Logged Out"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_log_a_user_id_735b81_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="audit_log_a_action__d48c20_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_log_a_content_bf31bf_idx",
                    ),
                ],
            },
        ),
    ]
