# Generated by Django 5.2.9 on 2026-01-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_log", "0002_auditlog_actor_email_auditlog_actor_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Created"),
                    ("UPDATE", "Updated"),
                    ("DELETE", "Deleted"),
                    ("STATUS_CHANGE", "Status Changed"),
                    ("PAYMENT_UPDATE", "Payment Status Changed"),
                    ("STOCK_ADJUSTMENT", "Stock Adjusted"),
                    ("APPOINTMENT_CANCEL", "Appointment Cancelled"),
                    ("USER_CREATE", "User Created"),
                    ("USER_UPDATE", "User Updated"),
                    ("USER_DELETE", "User Deleted"),
                    ("ROLE_CHANGE", "Role Changed"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("USER_DEACTIVATE", "User Deactivated"),
                    ("USER_REACTIVATE", "User Reactivated"),
                    ("LOGIN", "Logged In"),
                    ("LOGOUT", "Logged Out"),
                    ("SERVICE_ARCHIVE", "Service Archived"),
                    ("SERVICE_UNARCHIVE", "Service Unarchived"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
