# Generated by Django 5.2.8 on 2025-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        db_index=True,
                        help_text="Keyword to match (case-insensitive)",
                        max_length=200,
                    ),
                ),
                (
                    "response",
                    models.TextField(help_text="Bot response when keyword matches"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is active"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority rules match first (useful for specific vs general keywords)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chatbot Rule",
                "verbose_name_plural": "Chatbot Rules",
                "ordering": ["-priority", "keyword"],
            },
        ),
    ]
