# Generated by Django 5.2.8 on 2025-11-21 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_hours",
                    models.CharField(
                        default="Monday-Friday: 10:00 AM - 8:00 PM, Saturday: 10:00 AM - 6:00 PM, Sunday: Closed",
                        help_text="Business operating hours",
                        max_length=200,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Dreambook Salon, Manila, Philippines",
                        help_text="Business location/address",
                        max_length=500,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        default="+63 2 1234 5678",
                        help_text="Business phone number",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@dreambook.com",
                        help_text="Business email address",
                        max_length=254,
                    ),
                ),
                (
                    "max_daily_appointments",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum concurrent appointments per time slot",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chatbot Configuration",
                "verbose_name_plural": "Chatbot Configuration",
            },
        ),
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Session identifier for tracking conversation",
                        max_length=100,
                    ),
                ),
                ("user_message", models.TextField(help_text="Message from the user")),
                (
                    "bot_response",
                    models.TextField(help_text="Response from the chatbot"),
                ),
                (
                    "intent_detected",
                    models.CharField(
                        blank=True,
                        help_text="Detected intent/category of the message",
                        max_length=100,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score of intent detection (0-1)",
                    ),
                ),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="User feedback on whether response was helpful",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User having the conversation (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation History",
                "verbose_name_plural": "Conversation Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-created_at"],
                        name="chatbot_con_session_16845e_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="chatbot_con_user_id_7173e4_idx",
                    ),
                ],
            },
        ),
    ]
