# Generated by Django 5.2.8 on 2025-11-21 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_image_upload_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="downpayment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Downpayment amount required for this service",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="requires_downpayment",
            field=models.BooleanField(
                default=True,
                help_text="Whether a downpayment is required for this service",
            ),
        ),
    ]
