# Generated by Django 5.2.8 on 2025-11-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_service_downpayment_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Feature name (e.g., API, Hosting)", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS class for icon", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service Feature",
                "verbose_name_plural": "Service Features",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                help_text="Features included in this service",
                related_name="services",
                to="services.servicefeature",
            ),
        ),
    ]
