# Generated by Django 5.1.4 on 2025-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_servicefeature_service_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Whether this service is archived (soft delete)",
            ),
        ),
    ]
