# Generated by Django 5.2.9 on 2026-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_service_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("HAIR", "Hair Services"),
                    ("NAILS", "Nail Services"),
                    ("SKIN", "Skin Care"),
                    ("MAKEUP", "Makeup"),
                    ("SPA", "Spa & Massage"),
                    ("OTHER", "Other Services"),
                ],
                default="OTHER",
                help_text="Service category",
                max_length=20,
            ),
        ),
    ]
