# Generated by Django 5.2.8 on 2025-11-05 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Item name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Item description"),
                ),
                (
                    "unit",
                    models.CharField(
                        default="pcs",
                        help_text="Unit of measurement (e.g., pcs, ml, kg)",
                        max_length=50,
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current stock quantity",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Low stock alert threshold",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is actively tracked"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["name"],
            },
        ),
    ]
