# Generated by Django 5.2.9 on 2026-01-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("HAIR", "Hair Products"),
                    ("NAILS", "Nail Products"),
                    ("SKIN", "Skin Products"),
                    ("SUPPLIES", "General Supplies"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Item category",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="expiry_date",
            field=models.DateField(
                blank=True, help_text="Expiration date (optional)", null=True
            ),
        ),
    ]
