# Generated by Django 5.1.4 on 2025-12-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue Report"),
                            ("service_performance", "Service Performance"),
                            ("monthly_trends", "Monthly Trends"),
                        ],
                        help_text="Type of report",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Report title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Report description"),
                ),
                ("start_date", models.DateField(help_text="Report period start")),
                ("end_date", models.DateField(help_text="Report period end")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue for period",
                        max_digits=12,
                    ),
                ),
                (
                    "total_bookings",
                    models.IntegerField(default=0, help_text="Total bookings"),
                ),
                (
                    "completed_bookings",
                    models.IntegerField(default=0, help_text="Completed bookings"),
                ),
                (
                    "cancelled_bookings",
                    models.IntegerField(default=0, help_text="Cancelled bookings"),
                ),
                (
                    "no_show_bookings",
                    models.IntegerField(default=0, help_text="No-show bookings"),
                ),
                (
                    "total_refunds",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total refunds issued",
                        max_digits=12,
                    ),
                ),
                (
                    "net_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Revenue minus refunds",
                        max_digits=12,
                    ),
                ),
                (
                    "average_booking_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average booking amount",
                        max_digits=10,
                    ),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Completion rate percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "-generated_at"],
                        name="reports_rep_report__a7c87c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("service_bookings", "Service Bookings"),
                            ("service_revenue", "Service Revenue"),
                            ("daily_revenue", "Daily Revenue"),
                            ("payment_method", "Payment Method"),
                        ],
                        help_text="Type of metric",
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label for this metric (e.g., service name, date, method)",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, help_text="Numeric value", max_digits=12
                    ),
                ),
                ("count", models.IntegerField(default=0, help_text="Count of items")),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of total",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Associated report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Metric",
                "verbose_name_plural": "Report Metrics",
                "ordering": ["-value"],
            },
        ),
    ]
