# Generated by Django 5.2.8 on 2025-11-05 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_concurrent",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum concurrent appointments per time slot",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "booking_window_days",
                    models.IntegerField(
                        default=30,
                        help_text="How many days in advance customers can book",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "prevent_completion_on_insufficient_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Prevent appointment completion if inventory is insufficient",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Appointment Settings",
                "verbose_name_plural": "Appointment Settings",
            },
        ),
        migrations.CreateModel(
            name="BlockedRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField(help_text="Block start time")),
                ("end_at", models.DateTimeField(help_text="Block end time")),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for blocking (e.g., Holiday)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blocked Range",
                "verbose_name_plural": "Blocked Ranges",
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField(help_text="Appointment start time")),
                ("end_at", models.DateTimeField(help_text="Appointment end time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current appointment status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_state",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="unpaid",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who booked the appointment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service being booked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["start_at", "end_at"],
                        name="appointment_start_a_e8130c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_8fe9d7_idx"
                    ),
                ],
            },
        ),
    ]
