# Generated by Django 5.2.8 on 2025-11-18 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="The date for this slot limit")),
                ("time_start", models.TimeField(help_text="Start time (e.g., 09:00)")),
                ("time_end", models.TimeField(help_text="End time (e.g., 09:30)")),
                (
                    "max_slots",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum concurrent appointments for this time slot",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason for the slot limit (e.g., Staff absent)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Slot Limit",
                "verbose_name_plural": "Slot Limits",
                "ordering": ["date", "time_start"],
                "indexes": [
                    models.Index(
                        fields=["date", "time_start", "time_end"],
                        name="appointment_date_fca74c_idx",
                    )
                ],
                "unique_together": {("date", "time_start", "time_end")},
            },
        ),
    ]
