# Generated by Django 5.2.8 on 2025-11-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_slotlimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                    ("cancelled", "Cancelled"),
                ],
                default="confirmed",
                help_text="Current appointment status",
                max_length=20,
            ),
        ),
    ]
